### ISSUE TITLE
Optionally show time of pings

### ISSUE THREAD

**Issue by beterhans** [ThomasHabets/arping#20]
I need print time of every ping, but I can't see any type info for -m option

**Comment by ThomasHabets** [comment]
The timestamps in question are where the times are supposed to be taken from. E.g. some network cards are able to put a timestamp exactly when the packet arrived.

To see the list of possible values for `-m`, run with `-vv`.

This will not print the timestamp (wall clock time) of replies coming in. Sounds like a reasonable feature request. Is this what you meant?

**Comment by beterhans** [comment]
Wow thanks for you fast reply. yes I mean print the local system time for every message.
I'm check a problem that one router will stop reply any control message like arp at sometime and return to normal after a few seconds. I need to find the time slot of the issue.  when and how long it happened. so I googled and found your tool :) It helped me a lot Thanks any way.

**Comment by ThomasHabets** [comment]
I have another tool that could help you: https://github.com/ThomasHabets/ind

```
sudo ind -p '%c ' arping 192.168.0.1

Mon Oct 10 16:07:23 2016 ARPING 192.168.0.1
Mon Oct 10 16:07:23 2016 42 bytes from 00:00:11:22:33:44 (192.168.0.1): index=0 time=2.283 msec
Mon Oct 10 16:07:24 2016 42 bytes from 00:00:11:22:33:44 (192.168.0.1): index=1 time=2.185 msec
Mon Oct 10 16:07:25 2016 42 bytes from 00:00:11:22:33:44 (192.168.0.1): index=2 time=9.445 msec
Mon Oct 10 16:07:26 2016 42 bytes from 00:00:11:22:33:44 (192.168.0.1): index=3 time=1.854 msec
Mon Oct 10 16:07:26 2016 ^C
Mon Oct 10 16:07:26 2016 --- 192.168.0.1 statistics ---
Mon Oct 10 16:07:26 2016 4 packets transmitted, 4 packets received,   0% unanswered (0 extra)
Mon Oct 10 16:07:26 2016 rtt min/avg/max/std-dev = 1.854/3.941/9.445/3.181 ms
```

**Comment by beterhans** [comment]
WOW! thanks for the workaround!

**Comment by ThomasHabets** [comment]
Closing this since `ind` fixes the general case, and nobody else has requested this.
