### ISSUE TITLE
Harmonize flags between arping and iputils-arping

### ISSUE THREAD

**Issue by ZuZuD** [ThomasHabets/arping#22]
There is a conflict between these 2 packages options that can cause network trouble with ease.
iputils-arping use the option "-w" for timeout in second whereas arping use the same option for timeout in microseconds.

Installing a pgpool cluster (for example) from Ubuntu universe repository use by default the arping cmd for the gratuitous ARP Virtual IP.
arping_cmd = 'arping -U $_IP_$ -w 1'

Using by default the arping package instead of  iputils-arping can cause serious trouble to you network (tremendous layer2 broadcast).

A quick fix could be switching the -W (second) and -w flag  (microsecond) on arping package.
Seems to be a good idea to harmonize the flags for those 2 similar packages ?

**Comment by ThomasHabets** [comment]
Actually -w is a deadline in ping/iputils-arping, not a timeout.

I think I did it in microseconds in the past because the `ping` I was looking at did that. But that was over 16 years ago so I could be wrong or it could have changed.

I'll fix this.

**Comment by ZuZuD** [comment]
Thank you for your commit.
I should now return to scappy to test my network against crafted L2 fast broadcast ;)
