### ISSUE TITLE
configure: error: libnet 1.1.x not found

### ISSUE THREAD

**Issue by lirener** [ThomasHabets/arping#28]
configure: error: libnet 1.1.x not found
![434343](https://user-images.githubusercontent.com/19354130/33531308-2ac03b2e-d8c6-11e7-8832-92ace55039be.png)

使用msys64编译缺少libnet 1.1.x命令库文件 这要咋办？
(Use msys64 compile lack libnet 1.1 x command libraries What's the deal?)

**Comment by ThomasHabets** [comment]
I don't understand this question. Do you have libnet 1.1 or not? Have you confirmed that not only do you have libnet 1.1, but also that it works?

**Comment by lirener** [comment]
@ThomasHabets 
我好像没有 libnet 1.1 因为我是用windows to linux 是用叫 [msys2] 来实现的
(I don't like libnet 1.1 because I am using Windows to Linux is to use call [msys2])

**Comment by ThomasHabets** [comment]
I have no idea what that means.

**Comment by lirener** [comment]
Where can install libnet 1.1?（在哪里可以安装libnet 1.1？）

**Comment by lirener** [comment]
I have an old version of arping problems he can't achieve arping MAC to get IP instinct to new implementation?（我有一个旧版本的arping 问题他不能实现 arping MAC 来获取 IP 新版本能实现了吗？）
![23232](https://user-images.githubusercontent.com/19354130/33560833-e144d74e-d94b-11e7-9725-4d8392e9daa4.png)

**Comment by ThomasHabets** [comment]
On Windows? Don't know. There used to be a "libnetNT" that's libnet for Windows, but I've not looked at this in years. libnetNT is what someone else used (I think) to build the one you found.

**Comment by lirener** [comment]
I really want to install arping I got for a long time...Can you help me?（我真的很想安装 arping 我弄了好久了……可以帮帮我吗？）

**Comment by ThomasHabets** [comment]
You can start here: https://github.com/ThomasHabets/arping/issues/10

I'm not a Windows coder, so I won't be much help.

**Comment by lirener** [comment]
I've seen this but I don't know how to do it（这个我看过 但我不知道具体如何操作）
