### ISSUE TITLE
-bash: ./configure: No such file or directory ?

### ISSUE THREAD

**Issue by gelsas** [ThomasHabets/arping#29]
I am quite new to linux and I was trying to install arping on my raspberry pi (Rasbian).

So I downloaded the latest arping version from here https://github.com/ThomasHabets/arping/releases), put it on my raspberry pi and extracted the .tar.gz file. 

After that I tried to follow the instructions given in the Install file (https://github.com/ThomasHabets/arping/blob/arping-2.x/INSTALL)

When I try to follow the instructions I get this error:
```
[15:16:19] openhabian@openHABianPi:~$ cd arping-arping-2.19
[15:16:27] openhabian@openHABianPi:~/arping-arping-2.19$ ls
bootstrap.sh  doc    fuzz        INSTALL  Makefile.am         README
configure.ac  extra  HACKING.md  LICENSE  Makefile.am.common  src
[15:16:28] openhabian@openHABianPi:~/arping-arping-2.19$ ./configure
-bash: ./configure: No such file or directory
[15:17:51] openhabian@openHABianPi:~/arping-arping-2.19$ make
make: *** No targets specified and no makefile found.  Stop.
[15:17:51] openhabian@openHABianPi:~/arping-arping-2.19$ sudo make install
make: *** No rule to make target 'install'.  Stop.
[15:17:59] openhabian@openHABianPi:~/arping-arping-2.19$
```

**Comment by ThomasHabets** [comment]
(I've used tripple-backtick to format your comment better)

When downloading from github you need to run `./bootstrap.sh` first. That requires that you have autotools installed.

If you don't want to deal with that you can download [this](http://www.habets.pp.se/synscan/files/arping-2.19.tar.gz) which is the same but with these generated files (`configure` and friends) already generated.
