### ISSUE TITLE
No ./configure. Bootstrap looks for autoreconf which is not provided :/

### ISSUE THREAD

**Issue by phoenix84pl** [ThomasHabets/arping#31]
./bootstrap.sh: 2: ./bootstrap.sh: autoreconf: not found

Any ideas?

**Comment by ThomasHabets** [comment]
Install autoconf.

On debian/ubuntu:

```
apt-get install autoconf
```

You may also need `automake` and maybe `libtool`.

**Comment by phoenix84pl** [comment]
Worked. Thx!
