### ISSUE TITLE
libnet_get_hwaddr(): socket: Permission denied

### ISSUE THREAD

**Issue by lasyka** [ThomasHabets/arping#35]
When i run arping -i wlan0 192.x.x.x , get this error :
libnet_get_hwaddr(): socket: Permission denied.

I,m already use the root account to run it.
and i  wrote simple test code  to invoke libnet_get_hwaddr() ,there's no problem,and retun right hwcode.   Or run other app that uses libnet‘s method,also no problem.
only run arping ,get this error.

My env. is linux chroot on android phone:
Linux kali 3.10.40-lasyka+ #30 SMP PREEMPT Sat Sep 29 19:40:50 CST 2018 armv7l GNU/Linux

**Comment by ThomasHabets** [comment]
Could you add both:

1. The output of arping run with `-vvvvv`
2. The smaller test program, in full?

**Comment by lasyka** [comment]
> Could you add both:
> 
> 1. The output of arping run with `-vvvvv`
> 2. The smaller test program, in full?

Thanks for your help. use the vvvvv option got the drop uid/gid info.  And add -g option to run arping,the error is gone.

**Comment by ThomasHabets** [comment]
So you're saying Android doesn't have a group for "nobody"? What user did you choose with `-g`?

**Comment by ThomasHabets** [comment]
Oh right, this is https://github.com/ThomasHabets/arping/issues/25
