### ISSUE TITLE
unsupport libnet 1.2 and libnet 1.1.2.1

### ISSUE THREAD

**Issue by KevinLoveGitHub** [ThomasHabets/arping#40]
configure:4106: checking for libnet_name_resolve in -lnet
configure:4131: /Users/Kevin/Library/Android/sdk/ndk/21.1.6352462/toolchains/llvm/prebuilt/darwin-x86_64/bin/armv7a-linux-androideabi18-clang -o conftest -Wall -I/Users/Kevin/Workspaces/Compile/libnet-1.2/autotools-build/libnet/armeabi-v7a/include -I/Users/Kevin/Workspaces/Compile/libpcap-1.9.1/autotools-build/libpcap/armeabi-v7a/include -Wall -I/Users/Kevin/Workspaces/Compile/libnet-1.2/autotools-build/libnet/armeabi-v7a/include -I/Users/Kevin/Workspaces/Compile/libpcap-1.9.1/autotools-build/libpcap/armeabi-v7a/include -D_DEFAULT_SOURCE=1 -static -L/Users/Kevin/Workspaces/Compile/libnet-1.2/autotools-build/libnet/armeabi-v7a/lib -L/Users/Kevin/Workspaces/Compile/libpcap-1.9.1/autotools-build/libpcap/armeabi-v7a/lib conftest.c -lnet   >&5
/var/folders/0l/_d6bm6jn00qg6y8xm_mg10cc0000gn/T/conftest-1e4c45.o:conftest.c:function main: error: undefined reference to 'libnet_name_resolve'
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by ThomasHabets** [comment]
I'm guessing this was a mistake unrelated to arping. It really should work.
