### ISSUE TITLE
No buffer space available

### ISSUE THREAD

**Issue by 8Loading8** [ThomasHabets/arping#53]
Good afternoon.

I use the arping utility to check the availability of network nodes that do not respond to ping.
In the evenings I ran into the problem that arping does not work

`arping: lib net_write(): libnet_write_link(): only -1 bytes written (No buffer space available)`

During the day the macs in arp are about 4372 and in the evening when arping is not working about 4463
During the day, the traffic is about 4 Gbit/s and in the evening about 8 Gbit/s

```
net.ipv4.neigh.default.gc_thresh1 = 1280
net.ipv4.neigh.default.gc_thresh2 = 5120
net.ipv4.neigh.default.gc_thresh3 = 10240
```

I tried to increase gc_thresh by 2 times but it didn't help

Perhaps you need to make some kind of tuning of the linux kernel so that arping works in the evenings?

**Comment by ThomasHabets** [comment]
I don't think those parameters should help. They are all about the kernel's ARP table, I believe, but arping sends raw packets without looking consulting the ARP table.

More likely using `ifconfig` or `ip` to change the txqueuelength or something should be more effective, like `ip link set eth0 txqueuelen 2000`.

This could also help the rest of your performance. I wouldn't be super surprised if running 8Gbps on (presumably) a 10Gbps interface would start running a bit full on txqueues.

You may want to look into enabling multiqueue for the NIC, and QoS, if you're running that hot.

**Comment by 8Loading8** [comment]
It helped. Thanks.
